### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ewertonhm** [xwikisas/passbolt-toolbox#14]
Hi, i'm trying using your API, following the steps in the readme it gives me an error in the Server Setup:

(venv) administrador@UNI-TIO-0048:~/passbolt-toolbox$ ./passbolt-toolbox setup
*************************
Server setup
*************************
Server URI : http://192.168.65.145:81
Trust the server certficate without verification ? [yes / NO] yes
Traceback (most recent call last):
  File "/home/administrador/passbolt-toolbox/toolbox/./main.py", line 35, in <module>
    setupHelper.setupServer()
  File "/home/administrador/passbolt-toolbox/toolbox/setup.py", line 66, in setupServer
    self.passboltServer.fetchServerIdentity()
  File "/home/administrador/passbolt-toolbox/toolbox/passbolt.py", line 40, in fetchServerIdentity
    jsonResponse = self.api.auth.get()
  File "/home/administrador/passbolt-toolbox/venv/lib/python3.8/site-packages/passboltapi/auth.py", line 6, in get
    return self.manager.get(self.manager.buildURI('/auth/verify.json'))
  File "/home/administrador/passbolt-toolbox/venv/lib/python3.8/site-packages/passboltapi/meta.py", line 93, in get
    response = self.session.get(
AttributeError: 'NoneType' object has no attribute 'get'

Could it be because i'm running it without https?

**Comment by ewertonhm** [comment]
enabled https on the server, still getting the same error

(venv) administrador@UNI-TIO-0048:~/passbolt-toolbox$ ./passbolt-toolbox setup
*************************
Server setup
*************************
Server URI : https://192.168.65.145
Trust the server certficate without verification ? [yes / NO] yes
Traceback (most recent call last):
  File "/home/administrador/passbolt-toolbox/toolbox/./main.py", line 35, in <module>
    setupHelper.setupServer()
  File "/home/administrador/passbolt-toolbox/toolbox/setup.py", line 66, in setupServer
    self.passboltServer.fetchServerIdentity()
  File "/home/administrador/passbolt-toolbox/toolbox/passbolt.py", line 40, in fetchServerIdentity
    jsonResponse = self.api.auth.get()
  File "/home/administrador/passbolt-toolbox/venv/lib/python3.8/site-packages/passboltapi/auth.py", line 6, in get
    return self.manager.get(self.manager.buildURI('/auth/verify.json'))
  File "/home/administrador/passbolt-toolbox/venv/lib/python3.8/site-packages/passboltapi/meta.py", line 93, in get
    response = self.session.get(
AttributeError: 'NoneType' object has no attribute 'get'
